/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: 3d-coat (https://sketchfab.com/3d-coat)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/robot-steampunk-3d-coat-45-pbr-91eb0eb061024bf1bc5e3eb5ffe385d8
title: Robot Steampunk 3D-Coat 4.5 PBR
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/robot.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={0.015}>
          <mesh geometry={nodes.Object_2.geometry} material={materials.glass} />
          <mesh
            geometry={nodes.Object_3.geometry}
            material={materials.main_mat}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/robot.gltf");
